workflow:  
  - install
  - sail:parallel:
    - lint
    - test
  - build

tasks:
  install: &base
    image: node:11
    command:
      - npm
    args:
      - i
      - --ci
  lint:
    <<: *base
    args:
      - run
      - lint
  test:
    <<: *base
    args:
      - run
      - test

  build:
    <<: *base
    args:
      - run
      - build
